### PR TITLE
Update Tokio to 0.2.0-alpha.6

### PR DESCRIPTION
**Pull request by Majkl578**

### CODE REVIEW

**Comment by jtenner** [comment]
Hey this looks good! I'm just aware that this project was more of an example rather than a functioning library for production use. This is mostly because I'm not sure how to conform to the telnet specification. Any help with the algorithm would be greatly appreciated too.

**Comment by steven-joruk** [comment]
It'd be worth updating this to the latest tokio 0.2.x release.

> I'm just aware that this project was more of an example rather than a functioning library for production use. This is mostly because I'm not sure how to conform to the telnet specification.

It looks like a great start. I'd like to contribute if you have time to maintain this.

**Comment by jtenner** [comment]
@steven-joruk you are better off helping to contribute to https://github.com/huhlig/tokio-telnet which has a lot more direction than I currently do.

**Comment by jtenner** [comment]
Thank you for the praise, but this should be archived :)

**Pull request closed without merging**
